# Generated by Django 6.0.6 on 2026-09-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("authors", models.CharField(max_length=255, verbose_name="Authors")),
                ("category", models.CharField(max_length=100, verbose_name="Category")),
                (
                    "publisher",
                    models.CharField(max_length=100, verbose_name="Publisher"),
                ),
                ("published_year", models.IntegerField(verbose_name="Published year")),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                (
                    "aisle",
                    models.CharField(blank=True, max_length=10, verbose_name="Aisle"),
                ),
                (
                    "shelf",
                    models.CharField(blank=True, max_length=10, verbose_name="Shelf"),
                ),
                (
                    "bin",
                    models.CharField(blank=True, max_length=10, verbose_name="Bin"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Capacity"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Quantity"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cells",
                        to="warehouse.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cells",
                        to="warehouse.warehouse",
                        verbose_name="Warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell",
                "verbose_name_plural": "Cells",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("warehouse", "code"),
                        name="unique_cell_code_per_warehouse",
                    )
                ],
            },
        ),
    ]
