# Generated by Django 6.0.6 on 2026-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="ISBN"
            ),
        ),
    ]
